---
- hosts: win
  tasks:
   - name: Ensure user bob is present
     win_user:
      name: bob
      password: B0bP4ssw0rd
      password_never_expires: yes
      state: present
      groups:
       - Administrators